name: Feature request
description: 提出一个功能建议
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 想解决的问题
      description: 当前有什么不便 / 缺失？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案 / 权衡
    validations:
      required: false
